import { createBdd } from 'playwright-bdd';
import { test } from './fixtures';
import { expect } from '@playwright/test';
import { LoginPage } from '../../pages/LoginPage';


const { Given, When, Then } = createBdd(test);

//Login con usuario y contraseña
Given('que el usuario está en la página de login', async ({ loginPage }) => {
  await loginPage.goto();
});

When('introduce un nombre de usuario válido {string}', async ({ loginPage }, username: string) => {
  const user = username === 'ENV_USER' ? (process.env.USER_NAME || '') : username;
  await loginPage.fillUsername(user);
});

When('introduce una contraseña válida {string}', async ({ loginPage }, password: string) => {
  const pass = password === 'ENV_PASS' ? (process.env.USER_PASSWORD || '') : password;
  await loginPage.fillPassword(pass);
});

When('hace click en el botón {string}', async ({ loginPage }, boton: string) => {
  await loginPage.clickButton(boton);
});

Then('debería acceder a la aplicación', async ({ loginPage, homePage, page }) => {
  await loginPage.expectLoggedIn();
  await homePage.handleNotificationsPrompt(true).catch(() => null);
  try {
    const found = await page.locator('button:has-text("Activar"), text=Activar').evaluateAll((nodes: HTMLElement[]) =>
      nodes.map(n => ({ id: n.id, class: n.className, dataset: Object.assign({}, (n as any).dataset), outer: n.outerHTML.slice(0,300) }))
    );
    // eslint-disable-next-line no-console
    console.log('diag-activar-elements', JSON.stringify(found));
  } catch (e) {
    // ignore
  }
});

// Additional steps for validation and session scenarios
When('introduce un nombre de usuario inválido', async ({ loginPage }) => {
  const user = process.env.INVALID_USER || 'noexiste@example.com';
  await loginPage.fillUsername(user);
});

// Variant without parameter used in some scenarios
When('introduce un nombre de usuario válido', async ({ loginPage }) => {
  const user = process.env.USER_NAME || '';
  await loginPage.fillUsername(user);
});

When('introduce una contraseña inválida', async ({ loginPage }) => {
  const pass = process.env.INVALID_PASS || 'wrong-password';
  await loginPage.fillPassword(pass);
});

When('introduce credenciales inválidas', async ({ loginPage }) => {
  const user = process.env.INVALID_USER || 'noexiste@example.com';
  const pass = process.env.INVALID_PASS || 'wrong-password';
  await loginPage.fillUsername(user);
  await loginPage.fillPassword(pass);
});

When('introduce una contraseña válida', async ({ loginPage }) => {
  const pass = process.env.USER_PASSWORD || '';
  await loginPage.fillPassword(pass);
});

When('introduce un usuario válido', async ({ loginPage }) => {
  const user = process.env.TEST_USER || '';
  await loginPage.fillUsername(user);
});

Then('debería visualizar un mensaje de credenciales inválidas', async ({ loginPage }) => {
  await loginPage.expectInvalidCredentialsMessage();
});

Then('debería visualizar que el usuario es obligatorio', async ({ loginPage }) => {
  await loginPage.expectUsernameRequired();
});

Then('debería visualizar que la contraseña es obligatoria', async ({ loginPage }) => {
  await loginPage.expectPasswordRequired();
});

Then('debería visualizar los errores de validación', async ({ loginPage }) => {
  await loginPage.expectValidationErrors();
});

Then('debería visualizar el dashboard', async ({ loginPage, homePage, page }) => {
  await loginPage.expectLoggedIn();
  await homePage.handleNotificationsPrompt(true).catch(() => null);
});

Then('debería visualizar su nombre de usuario', async ({ loginPage }) => {
  await loginPage.expectUsernameVisible();
});

// Missing step synonyms generated by bddgen
Then('debería ser redirigido al dashboard', async ({ loginPage }) => {
  await loginPage.expectLoggedIn();
});

When('inicia sesión con credenciales válidas', async ({ loginPage, homePage, page }) => {
  const user = process.env.USER_NAME || '';
  const pass = process.env.USER_PASSWORD || '';
  await loginPage.fillUsername(user);
  await loginPage.fillPassword(pass);
  await loginPage.clickButton('Iniciar sesión');
  await loginPage.expectLoggedIn();
  await homePage.handleNotificationsPrompt(true).catch(() => null);
});

Then('debería acceder directamente al dashboard', async ({ page }) => {
  const { DASHBOARD_URL } = await import('../../pages/urls');
  await page.waitForURL(DASHBOARD_URL);
});

Then('debería ser redirigido al login', async ({ page }) => {
  const { LOGIN_URL } = await import('../../pages/urls');
  await page.waitForURL(LOGIN_URL);
});

Given('que el usuario ha iniciado sesión', async ({ loginPage, homePage }) => {
  await loginPage.goto();
  const user = process.env.USER_NAME || '';
  const pass = process.env.USER_PASSWORD || '';
  await loginPage.fillUsername(user);
  await loginPage.fillPassword(pass);
  await loginPage.clickButton('Iniciar sesión');
  await loginPage.expectLoggedIn();
  await homePage.handleNotificationsPrompt(true).catch(() => null);
});

Given('que el usuario ya tiene sesión iniciada', async ({ loginPage, homePage }) => {
  // reuse the login flow to create a session for the current context
  const user = process.env.USER_NAME || '';
  const pass = process.env.USER_PASSWORD || '';
  await loginPage.goto();
  await loginPage.fillUsername(user);
  await loginPage.fillPassword(pass);
  await loginPage.clickButton('Iniciar sesión');
  await loginPage.expectLoggedIn();
  await homePage.handleNotificationsPrompt(true).catch(() => null);
});

When('accede a la aplicación', async ({ page }) => {
  const { INDEX_URL } = await import('../../pages/urls');
  await page.goto(INDEX_URL);
});

When('accede directamente al dashboard', async ({ page }) => {
  const { DASHBOARD_URL } = await import('../../pages/urls');
  await page.goto(DASHBOARD_URL);
});

When('hace click en cerrar sesión', async ({ page }) => {
  const boton = page.getByText('Cerrar sesión');
  await boton.waitFor({ state: 'visible', timeout: 5000 }).catch(() => null);
  await boton.click().catch(() => null);
});

Then('debería volver a la página de login', async ({ page }) => {
  const { LOGIN_URL } = await import('../../pages/urls');
  await page.waitForURL(LOGIN_URL);
});




